# Generated by Django 5.2.1 on 2025-06-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade_pessoas', models.PositiveIntegerField()),
                ('data_evento', models.DateField()),
                ('horario', models.TimeField()),
                ('descricao', models.TextField(blank=True, max_length=250)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ClientesEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('qtd_cadeira', models.PositiveIntegerField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='api.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Cadeiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_assent', models.CharField(max_length=10)),
                ('column_assent', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], max_length=20)),
                ('id_setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeiras', to='api.setores')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
