# Generated by Django 5.2.1 on 2025-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='STATUS', max_length=9)),
            ],
            options={
                'db_table': 'cadeira',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=50)),
                ('e_mail', models.CharField(db_column='E_MAIL', max_length=50)),
                ('cpf', models.CharField(db_column='CPF', max_length=14)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=50)),
                ('qtd_publico', models.FloatField(db_column='QTD_PUBLICO')),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=50)),
                ('qtd_cadeira', models.FloatField(db_column='QTD_CADEIRA')),
            ],
            options={
                'db_table': 'setor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetorCliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'setor_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=50, null=True)),
                ('e_mail', models.CharField(blank=True, db_column='E_MAIL', max_length=50, null=True)),
                ('senha', models.CharField(blank=True, db_column='SENHA', max_length=260, null=True)),
                ('perfil', models.CharField(db_column='PERFIL', max_length=13)),
                ('cpf', models.CharField(db_column='CPF', max_length=14)),
                ('login', models.CharField(db_column='LOGIN', max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
